[package]
name = "adam_token"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[lib]
sierra = true

[[target.starknet-contract]]
name = "adam_token"
sierra = true
