[workspace]
members = [
    "packages/adam-token",
    "packages/adam-pool",
    "packages/adam-swap",
]

[workspace.dependencies]
starknet = "2.15.0"
openzeppelin = "2.0.0"
snforge_std = "0.56.0"
adam_token = { path = "packages/adam-token" }
adam_pool = { path = "packages/adam-pool" }
adam_swap = { path = "packages/adam-swap" }

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
