[package]
name = "adam_swap"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
adam_token.workspace = true
adam_pool.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[lib]
sierra = true

[[target.starknet-contract]]
sierra = true
